---
Name: imagesliderconfig
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Loyals\ImageSlider\Extensions\ImageSliderPageExtension

PageController:
  extensions:
    - Loyals\ImageSlider\Extensions\ImageSliderControllerInit

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Loyals\ImageSlider\Extensions\ImageSliderSiteConfigExtension

ImageSliderConfig:
  PageTypeExcludes:
    - SilverStripe\CMS\Model\VirtualPage
    - SilverStripe\ErrorPage\ErrorPage
    - SilverStripe\CMS\Model\RedirectorPage
    - SilverStripe\Blog\Model\Blog
    - SilverStripe\Blog\Model\BlogPost
